@startuml All-GUI

abstract class AbstractGridBagLayoutJComponent {
    c : GridBagConstraints
}

class AchievementLabel {
    iconLabel : JLabel
    nameLabel : JLabel
    descriptionLabel : JLabel

    + toString() : String
    + getIcon() : ImageIcon
    + getName() : String
    + getDescription() : String
}

class AchievementsPanel {
}

class AchievementLabelCellRenderer {
    iconSize : int
    
    + getListCellRendererComponent( Soo many parameters lmao ) : Component
}

class ArenaLabel {
    enemyField : JLabel
    playerField : JLabel
    enemyButton : JButton
    playerButton : JButton
    puckButton : JButton

    + getEnemyField() : JLabel
    + getPlayerField() : JLabel
    + getEnemyButton() : JButton
    + getPlayerButton() : JButton
    + getPuckButton() : JButton
}

class ExceptionPanel {
}

class GameOverPanel {
}

class GamePanel {
    serialVersionUID : long
    game : GameState
    delay : int
    timer : Timer
    arenaLabel : ArenaLabel
    playerScoreLabel : JLabel
    enemyScoreLabel : JLabel
    pauseButton : JButton
    uc : UnitConverter
    isMainPlayerMoving : boolean
    mouseHandler : MousePhysicsHandler

    + startGame() : void
    - updateGame() : void
    - endGame() : void
    - updatePositions() : void
}

class GUI {
    + getScreenSize() : Dimension
    + getMinScreenSize() : Dimension
    + setFont() : void
}

class IconButton {
}

class Main {
}

class MenuPanel {
}

class PausePanel {
    serialVersionUID : long
    gameState : GameState
}

class SettingsPanel {
    serialVersionUID : long
    themeArray[] : Theme
    difficultyArray[] : Difficulty

    + addComponent( component : JComponent, x : int, y : int )
}

abstract class AbstractGridBagLayoutJComponent extends JComponent
class AchievementLabel extends JLabel
class AchievementsPanel extends JScrollPane
AchievementLabelCellRenderer --* AchievementsPanel
class ArenaLabel extends JLabel
class GameOverPanel extends AbstractGridBagLayoutJComponent
class GamePanel extends AbstractGridBagLayoutJComponent
class GUI extends JFrame
class IconButton extends JButton
GUI --* Main
class MenuPanel extends AbstractGridBagLayoutJComponent
class PausePanel extends AbstractGridBagLayoutJComponent
class SettingsPanel extends AbstractGridBagLayoutJComponent

@enduml