name: compile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install OpenJDK 11 and Maven
        run: sudo apt update && sudo apt install openjdk-11-jdk maven
      
      - name: Download Maven dependencies into lib/
        run: |
          mvn install dependency:copy-dependencies
          mv target/dependency/* lib/

      - name: Compile only Main dependencies
        run: javac -sourcepath src -cp lib/* -d out src/gui/Main.java

      - name: Compile all source files
        run: find src -name "*.java" -print | xargs javac -cp lib/* -d out

      - name: Make JAR archive
        run: find out -print | xargs jar cf air-hockey.jar
